"""create_network_flows_table

Revision ID: c708aff9a027
Revises: 54285f278ef6
Create Date: 2026-09-24 17:09:38.165970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c708aff9a027'
down_revision: Union[str, Sequence[str], None] = '54285f278ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('destination_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('flow_duration', sa.Float(), nullable=False),
    sa.Column('packet_count', sa.BigInteger(), nullable=False),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('packet_rate', sa.Float(), nullable=False),
    sa.Column('byte_rate', sa.Float(), nullable=False),
    sa.Column('flags', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('dataset_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('destination_port >= 0 AND destination_port <= 65535', name='check_dest_port_range'),
    sa.CheckConstraint('source_port >= 0 AND source_port <= 65535', name='check_source_port_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flows_src_dst', 'network_flows', ['source_ip', 'destination_ip'], unique=False)
    op.create_index('idx_flows_timestamp_desc', 'network_flows', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_network_flows_destination_ip'), 'network_flows', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_network_flows_id'), 'network_flows', ['id'], unique=False)
    op.create_index(op.f('ix_network_flows_label'), 'network_flows', ['label'], unique=False)
    op.create_index(op.f('ix_network_flows_protocol'), 'network_flows', ['protocol'], unique=False)
    op.create_index(op.f('ix_network_flows_source_ip'), 'network_flows', ['source_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_flows_source_ip'), table_name='network_flows')
    op.drop_index(op.f('ix_network_flows_protocol'), table_name='network_flows')
    op.drop_index(op.f('ix_network_flows_label'), table_name='network_flows')
    op.drop_index(op.f('ix_network_flows_id'), table_name='network_flows')
    op.drop_index(op.f('ix_network_flows_destination_ip'), table_name='network_flows')
    op.drop_index('idx_flows_timestamp_desc', table_name='network_flows')
    op.drop_index('idx_flows_src_dst', table_name='network_flows')
    op.drop_table('network_flows')
    # ### end Alembic commands ###
