"""create detections table

Revision ID: f9ad4bdbf2c8
Revises: 1890677b009e
Create Date: 2026-09-24 17:26:41.691077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ad4bdbf2c8'
down_revision: Union[str, Sequence[str], None] = '1890677b009e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('predicted_attack', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('severity_reason', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['network_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detections_attack_timestamp', 'detections', ['predicted_attack', 'timestamp'], unique=False)
    op.create_index('idx_detections_severity_timestamp', 'detections', ['severity', 'timestamp'], unique=False)
    op.create_index(op.f('ix_detections_flow_id'), 'detections', ['flow_id'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_detections_predicted_attack'), 'detections', ['predicted_attack'], unique=False)
    op.create_index(op.f('ix_detections_severity'), 'detections', ['severity'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index(op.f('ix_detections_severity'), table_name='detections')
    op.drop_index(op.f('ix_detections_predicted_attack'), table_name='detections')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_flow_id'), table_name='detections')
    op.drop_index('idx_detections_severity_timestamp', table_name='detections')
    op.drop_index('idx_detections_attack_timestamp', table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
